###### VERİ ANALİZİ -NUMPY

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [6]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
rast=np.random.rand(3,4)
rast

array([[0.23918291, 0.86787231, 0.88919048, 0.60922434],
       [0.90777006, 0.40907709, 0.97786466, 0.8369279 ],
       [0.71796572, 0.74247543, 0.90876232, 0.38532002]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
y=np.arange(24)
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
import numpy as np

In [7]:
a=np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
a[3:6]

array([ 9, 16, 25], dtype=int32)

In [15]:
y=np.random.random(16)
y.reshape(4,4)


array([[0.34699811, 0.21695832, 0.83103067, 0.46210056],
       [0.08911265, 0.51841159, 0.52431458, 0.85123485],
       [0.69494523, 0.01687761, 0.40194255, 0.08399243],
       [0.06579248, 0.24757634, 0.85927698, 0.40189736]])

In [19]:
y[2:1]

array([], dtype=float64)

In [23]:
for satır in y.flat:
    print(satır)

0.34699810952528
0.216958321424371
0.831030665026064
0.4621005574147322
0.08911265097077159
0.5184115901726549
0.5243145831650723
0.8512348512935448
0.6949452285436626
0.016877611805272363
0.4019425488539111
0.08399242569034471
0.0657924764669292
0.2475763424007128
0.859276975819045
0.4018973615517052


In [24]:
a=np.array([2,3])
b=np.array([4,5])

In [25]:
np.hstack((a,b))

array([2, 3, 4, 5])

In [26]:
np.vstack((a,b))

array([[2, 3],
       [4, 5]])

In [27]:
şehir =np.array(["ankara","istanbul","izmir","bursa","izmir","bursa"])
np.unique(şehir)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')

#### Egzersizler

In [28]:
import numpy as np

In [31]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [42]:
a=np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a=np.ones((3,5))*7
a

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [45]:
a=np.arange(10,70,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

In [58]:
a=np.random.rand(3,4)
a

array([[0.12284339, 0.96152873, 0.92679125, 0.6741272 ],
       [0.09812462, 0.87804277, 0.84605542, 0.3616138 ],
       [0.53409153, 0.3781839 , 0.92354936, 0.88436329]])

In [59]:
a=np.random.random(10)
a

array([0.08486866, 0.0528823 , 0.89267644, 0.85032281, 0.01216324,
       0.16369136, 0.26604968, 0.76110854, 0.24782229, 0.37692581])

In [61]:
x=np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
x=np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [64]:
x.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [67]:
a=np.random.random(10)
a

array([0.54177494, 0.02761995, 0.1335215 , 0.55502178, 0.05263196,
       0.1013339 , 0.32068904, 0.73419215, 0.81584935, 0.90192444])

In [68]:
a.max()

0.901924439149603

In [69]:
a.min()

0.027619949630347196

In [70]:
x=np.random.rand(4,4)
x

array([[0.2078775 , 0.04993786, 0.66554269, 0.86065504],
       [0.2056128 , 0.45890176, 0.05095026, 0.26652519],
       [0.64596592, 0.54741769, 0.0202647 , 0.32528189],
       [0.31845667, 0.14407114, 0.10235233, 0.6792547 ]])

In [73]:
x[2] #ikinci satırdaki elemanları çektim

array([0.64596592, 0.54741769, 0.0202647 , 0.32528189])

In [77]:
x[:4] #dördüncü sütundaki elemanları çektim

array([[0.2078775 , 0.04993786, 0.66554269, 0.86065504],
       [0.2056128 , 0.45890176, 0.05095026, 0.26652519],
       [0.64596592, 0.54741769, 0.0202647 , 0.32528189],
       [0.31845667, 0.14407114, 0.10235233, 0.6792547 ]])

In [81]:
x[3,3] # 3.satır 3.sütundaki elemanı aldım 

0.6792547003370664

In [82]:
for sayı in x.flat:
    print(sayı)

0.2078775039287183
0.049937861089373925
0.6655426911217701
0.8606550404355378
0.20561280257562808
0.45890175539068645
0.05095025697818756
0.2665251851277649
0.6459659235098609
0.547417690359117
0.02026470264665403
0.32528189276341457
0.31845666677394635
0.14407113983986286
0.10235233171173674
0.6792547003370664


In [83]:
x=np.random.random(4)
x

array([0.87577428, 0.73411361, 0.16275182, 0.94584689])

In [84]:
x*5

array([4.37887142, 3.67056807, 0.81375912, 4.72923443])

In [85]:
x.sum()

2.7184866094854225

In [86]:
np.std(x)

0.30800792347831385

In [87]:
np.var(x)

0.09486888092542285